// src/components/SegwitSendPanel.vue
<script setup>
/*
 * Spending the SegWit chain, on the Send page where spending belongs.
 *
 * It used to live only inside PlainAddressPanel.vue on the wallet card — the
 * panel that hands out the address — so paying from it meant going to the
 * receiving surface in order to send. The browser half of
 * components/SegwitSendPanel.tsx; the two apps answer this the same way.
 *
 * Deliberately not folded into the Silent Payments form beside it. They look
 * similar and are not: this chain is walked in the browser, picks coins BY
 * ADDRESS rather than by outpoint, has its own fee arithmetic in
 * services/plainSign.ts, and cannot share a transaction with an SP coin. One
 * form doing both would branch at every field, and the branch nobody noticed
 * would be the one that signs.
 */
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { useAuthStore } from '@/stores/auth'
import * as api from '@/api'
import { loadPlainChain, plainAddressTotals } from '@/services/plainChain'
import { getSegwitLabel } from '@/stores/segwitlabels'
import PlainSendModal from './PlainSendModal.vue'

const props = defineProps({
  wallet: { type: Object, required: true },
})

const auth = useAuthStore()

const accountXprv = ref('')
const chain       = ref(null)
const totals      = ref([])
const loading     = ref(false)
const error       = ref(null)
const sendOpen    = ref(false)

// A payment already broadcast that the chain index has not caught up with. Its
// inputs are spent, and offering them again builds a conflicting transaction —
// the same guard PlainAddressPanel carries.
const pendingSpend = ref(null)
const SPEND_STALE_MS = 15 * 60 * 1000

const sats     = computed(() => chain.value?.confirmedSats ?? 0)
const arriving = computed(() => chain.value?.unconfirmedSats ?? 0)
const inFlight = computed(() => !!pendingSpend.value)
const canSend  = computed(
  () => !inFlight.value && sats.value > 0 && !!accountXprv.value &&
        !!chain.value?.fundedIndices.length,
)

function groupThousands(n) {
  return Math.floor(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')
}

function shortAddress(s) {
  const a = String(s || '')
  return a.length > 20 ? `${a.slice(0, 10)}…${a.slice(-8)}` : a
}

function labelOf(address) {
  return getSegwitLabel(props.wallet?.id, address)
}

let lastWalkAt = 0

async function refresh() {
  const keys = await auth.getWalletKeys(props.wallet.id)
  accountXprv.value = keys?.sweepAccount || ''
  if (!accountXprv.value) { chain.value = null; return }
  loading.value = true
  error.value = null
  lastWalkAt = Date.now()
  try {
    const next = await loadPlainChain(
      (addresses) => api.getPlainPreview(auth.inkey, props.wallet.id, addresses),
      accountXprv.value,
      props.wallet.network,
    )
    chain.value = next
    totals.value = plainAddressTotals(next)
    if (
      pendingSpend.value &&
      (Date.now() - pendingSpend.value.at > SPEND_STALE_MS ||
        next.confirmedSats !== pendingSpend.value.balanceAtSpend)
    ) {
      pendingSpend.value = null
    }
  } catch (e) {
    error.value = e.message || 'Could not check your SegWit addresses.'
  } finally {
    loading.value = false
  }
}

function onSent(txid) {
  pendingSpend.value = {
    txid,
    balanceAtSpend: chain.value?.confirmedSats ?? 0,
    at: Date.now(),
  }
}

// The same watcher as the receive panel, and for the same reason: there is no
// Refresh button on either, and `check_plain_preview_allowed` on the server
// holds this endpoint to thirty a minute per account. The guards are the three
// that panel documents — not under an open send modal, which is handed `chain`
// as a prop; not a hidden tab; not on top of a walk already running.
const POLL_MS = 5 * 60 * 1000
let timer = null

function pollable() {
  return (
    !!accountXprv.value &&
    !loading.value &&
    !sendOpen.value &&
    document.visibilityState === 'visible'
  )
}

function tick() {
  if (pollable()) refresh()
}

function onVisible() {
  if (
    document.visibilityState === 'visible' &&
    Date.now() - lastWalkAt >= POLL_MS
  ) {
    tick()
  }
}

onMounted(() => {
  refresh()
  timer = setInterval(tick, POLL_MS)
  document.addEventListener('visibilitychange', onVisible)
})

onUnmounted(() => {
  if (timer) clearInterval(timer)
  timer = null
  document.removeEventListener('visibilitychange', onVisible)
})

// Switching wallet on the Send page must re-walk: the account key and the
// whole chain belong to one wallet, and leaving the old one on screen would
// offer coins the selected wallet does not own.
watch(() => props.wallet?.id, refresh)
watch(() => auth.keysVersion, refresh)
</script>

<template>
  <div>
    <div v-if="loading && !chain" class="text-dim text-sm">Checking…</div>

    <div v-else-if="!accountXprv" class="alert alert-warn">
      This wallet predates SegWit addresses. Open its card on Wallets to set
      them up with your recovery phrase.
    </div>

    <template v-else>
      <div class="card" style="margin-bottom:16px">
        <div class="card-body" style="text-align:center">
          <div class="text-dim text-xs">
            {{ inFlight ? 'Payment on its way' : 'Available to send' }}
          </div>
          <b v-if="!inFlight" style="font-size:22px;display:block;margin-top:4px">
            {{ groupThousands(sats) }} sats
          </b>
          <div v-else class="text-dim text-xs" style="margin-top:4px">
            Waiting for the chain index to catch up
          </div>
          <div v-if="!inFlight && arriving > 0" class="text-dim text-xs" style="margin-top:6px">
            + {{ groupThousands(arriving) }} sats waiting to be mined
          </div>
        </div>
      </div>

      <!-- WHICH ADDRESSES the money is on, with whatever they were called. The
           picker inside the send modal chooses between addresses, so this is
           the same list it will offer: "send from where" is worth deciding
           before the form opens. -->
      <div v-if="totals.length && !inFlight" class="card" style="margin-bottom:16px">
        <div class="card-body" style="padding:0">
          <div v-for="t in totals" :key="t.address" class="segwit-row">
            <div style="min-width:0">
              <div style="font-size:14px">{{ labelOf(t.address) || shortAddress(t.address) }}</div>
              <div v-if="labelOf(t.address)" class="mono text-dim text-xs" style="margin-top:2px">
                {{ shortAddress(t.address) }}
              </div>
            </div>
            <b class="text-sm">{{ groupThousands(t.sats) }} sats</b>
          </div>
        </div>
      </div>

      <div v-if="error" class="alert alert-error" style="margin-bottom:16px">⚠ {{ error }}</div>

      <button class="btn btn-primary" :disabled="!canSend" @click="sendOpen = true">
        Send SegWit coins
      </button>

      <p v-if="!canSend && !inFlight" class="text-dim text-xs" style="margin-top:10px">
        Nothing here yet. Receive to a SegWit address first.
      </p>
    </template>

    <PlainSendModal
      :show="sendOpen"
      :wallet="wallet"
      :account-xprv="accountXprv"
      :chain="chain"
      @sent="onSent"
      @close="sendOpen = false; refresh()"
    />
  </div>
</template>

<style scoped>
.segwit-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 10px 14px;
  border-bottom: 1px solid var(--border);
}
.segwit-row:last-child { border-bottom: none; }
</style>

// src/components/SegwitSendPanel.tsx
import React, { useCallback, useEffect, useState } from 'react';
import {
  ActivityIndicator,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import * as api from '@services/api';
import { useAuthStore } from '@stores/authStore';
import { getWalletKeys } from '@services/secureKeys';
import {
  loadPlainChain,
  plainAddressTotals,
  PlainAddressTotal,
  PlainChainState,
} from '@services/plainChain';
import { labelFor } from '@services/segwitLabels';
import { useSegwitLabels } from '@stores/segwitLabelStore';
import { usePlainStatus, plainSpendSettled } from '@stores/plainStatus';
import PlainSendModal from './PlainSendModal';
import { colors } from '@/theme';
import { MASK, useBalancesHidden } from '@stores/balancePrivacy';

function groupThousands(n: number): string {
  return Math.floor(n)
    .toString()
    .replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

function truncateMiddle(s: string, head = 10, tail = 8): string {
  if (s.length <= head + tail + 1) return s;
  return `${s.slice(0, head)}…${s.slice(-tail)}`;
}

interface Props {
  wallet: api.SilntWallet;
}

/**
 * Spending the SegWit chain, on the Send tab where spending belongs.
 *
 * It used to live only on the Receive tab, inside the card that hands out the
 * address — reached by going to Receive in order to send, which is the wrong
 * place by the name of the tab. The card keeps the receiving half; this is the
 * paying half, and the two are different jobs.
 *
 * Deliberately not folded into the Silent Payments form above it. They look
 * similar and are not: this chain is walked on the device, picks coins BY
 * ADDRESS rather than by outpoint, has its own fee arithmetic in
 * services/plainSign.ts, and cannot share a transaction with an SP coin. One
 * form pretending to do both would have to branch at every field, and the
 * branch nobody noticed would be the one that signs.
 */
export default function SegwitSendPanel({ wallet }: Props) {
  const hidden = useBalancesHidden();
  const inkey = useAuthStore((s) => s.inkey);
  const labels = useSegwitLabels((s) => s.byWallet);
  // A payment already broadcast that the chain index has not caught up with.
  // Its inputs are spent, and offering them again builds a conflicting
  // transaction — the same guard the Receive card carries.
  const pendingSpend = usePlainStatus((s) => s.pendingSpend);

  const [accountXprv, setAccountXprv] = useState<string | null>(null);
  const [chain, setChain] = useState<PlainChainState | null>(null);
  const [totals, setTotals] = useState<PlainAddressTotal[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [sendOpen, setSendOpen] = useState(false);

  const refresh = useCallback(async () => {
    if (!inkey) return;
    const keys = await getWalletKeys(wallet.id);
    const xprv = keys?.sweepAccount || null;
    setAccountXprv(xprv);
    if (!xprv) {
      setChain(null);
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const next = await loadPlainChain(
        (addresses) => api.getPlainPreview(inkey, wallet.id, addresses),
        xprv,
        wallet.network,
      );
      setChain(next);
      setTotals(plainAddressTotals(next));
      if (
        plainSpendSettled(usePlainStatus.getState().pendingSpend, next.confirmedSats)
      ) {
        usePlainStatus.getState().clearSpent();
      }
      // Publish what this walk learned, so the wallet screen's total reflects
      // it without waiting for the watcher's next poll.
      usePlainStatus.getState().set({
        walletId: wallet.id,
        spendableSats: next.confirmedSats,
        unconfirmedSats: next.unconfirmedSats,
      });
    } catch (e: any) {
      setError(e?.message || 'Could not check your SegWit addresses.');
    } finally {
      setLoading(false);
    }
  }, [inkey, wallet.id, wallet.network]);

  // Re-walked when the watcher finds the totals changed, same as the Receive
  // card — there is no Refresh button on either any more.
  const observedAt = usePlainStatus((s) => s.observedAt);
  useEffect(() => {
    refresh();
  }, [refresh, observedAt]);

  const sats = chain?.confirmedSats ?? 0;
  const inFlight = !!pendingSpend;
  const canSend = !inFlight && sats > 0 && !!accountXprv && !!chain?.fundedIndices.length;

  if (loading && !chain) {
    return <ActivityIndicator color={colors.primary} style={styles.spinner} />;
  }

  if (!accountXprv) {
    return (
      <Text style={styles.note}>
        This wallet predates SegWit addresses. Open the Receive tab to set them
        up with your recovery phrase.
      </Text>
    );
  }

  return (
    <View>
      <View style={styles.balanceBox}>
        <Text style={styles.balanceLabel}>
          {inFlight ? 'Payment on its way' : 'Available to send'}
        </Text>
        {inFlight ? (
          <Text style={styles.balanceHint}>
            Waiting for the chain index to catch up
          </Text>
        ) : (
          <Text style={styles.balanceValue}>
            {hidden ? MASK : groupThousands(sats)} sats
          </Text>
        )}
        {!inFlight && chain && chain.unconfirmedSats > 0 ? (
          <Text style={styles.balanceHint}>
            + {hidden ? MASK : groupThousands(chain.unconfirmedSats)} sats waiting
            to be mined
          </Text>
        ) : null}
      </View>

      {/* WHICH ADDRESSES the money is on, with whatever the user called them.
          The picker inside the send modal chooses between addresses, so this
          is the same list it will offer — shown first, because "send from
          where" is a decision worth making before the form opens. */}
      {totals.length > 0 && !inFlight ? (
        <View style={styles.list}>
          {totals.map((t) => {
            const label = labelFor(labels, wallet.id, t.address);
            return (
              <View key={t.address} style={styles.row}>
                <View style={styles.rowText}>
                  <Text style={styles.rowName} numberOfLines={1}>
                    {label || truncateMiddle(t.address)}
                  </Text>
                  {label ? (
                    <Text style={styles.rowSub} numberOfLines={1}>
                      {truncateMiddle(t.address)}
                    </Text>
                  ) : null}
                </View>
                <Text style={styles.rowSats}>
                  {hidden ? MASK : groupThousands(t.sats)} sats
                </Text>
              </View>
            );
          })}
        </View>
      ) : null}

      {error ? <Text style={styles.error}>{error}</Text> : null}

      <TouchableOpacity
        style={[styles.primaryBtn, !canSend && styles.btnDisabled]}
        onPress={() => setSendOpen(true)}
        disabled={!canSend}>
        <Text style={styles.primaryBtnText}>Send SegWit coins</Text>
      </TouchableOpacity>

      {!canSend && !inFlight ? (
        <Text style={styles.note}>
          Nothing here yet. Receive to a SegWit address first.
        </Text>
      ) : null}

      {sendOpen && accountXprv && chain ? (
        <PlainSendModal
          visible
          wallet={wallet}
          accountXprv={accountXprv}
          chain={chain}
          // Re-walked on the way OUT, not at broadcast: refreshing under an
          // open modal churns the chain it was opened with, and the index has
          // not seen the spend that soon anyway.
          onClose={() => {
            setSendOpen(false);
            refresh();
          }}
          onSpent={(txid) =>
            usePlainStatus.getState().markSpent({
              txid,
              balanceAtSpend: chain.confirmedSats,
              at: Date.now(),
            })
          }
        />
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  spinner: { marginTop: 24 },
  balanceBox: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 10,
    padding: 14,
    alignItems: 'center',
  },
  balanceLabel: { fontSize: 12, color: colors.muted },
  balanceValue: { fontSize: 22, fontWeight: '700', color: colors.text, marginTop: 4 },
  balanceHint: { fontSize: 11, color: colors.faint, marginTop: 6, textAlign: 'center' },
  list: {
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  rowText: { flex: 1, paddingRight: 10 },
  rowName: { fontSize: 14, color: colors.text },
  rowSub: { fontFamily: 'monospace', fontSize: 11, color: colors.faint, marginTop: 2 },
  rowSats: { fontSize: 13, color: colors.text, fontWeight: '600' },
  primaryBtn: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 18,
  },
  primaryBtnText: { color: colors.onPrimary, fontSize: 16, fontWeight: '600' },
  btnDisabled: { opacity: 0.4 },
  note: { fontSize: 12, color: colors.faint, marginTop: 12, textAlign: 'center' },
  error: { color: colors.danger, fontSize: 13, marginTop: 14, textAlign: 'center' },
});
